#!/bin/sh

# Copyright (C) 2023 NeonOrbit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if ! java --version 2>/dev/null 1>&2; then
    echo "Please install JDK" && exit 1
fi

if [ "$1" = "java" ]; then
    javac -d classes source/test/*.java   # .java to .class
    zip classes.zip classes/*   # .class to .zip
    d8 --output out classes.zip   # .zip to .dex
elif [ "$1" = "smali"  ]; then
    java -jar smali.jar source/test/*.smali   # .smali to .dex
fi
